version: '2'

services:
  db:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - /var/lib/mongodb/data
    ports:
      - 27017:27017

  website:
    depends_on:
      - 'db'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/src/app'
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
